language: node_js
node_js:
  - "stable"
before_install:
    - npm install -g tslint typescript typedoc
    
script:
    - npm run tsc:ci
    - npm run test:ci
    - npm run docs
notifications:
  email:
    - bdash4@sapient.com
    - biswajit639@yahoo.com 