language: node_js
node_js:
  - "stable"
before_install:
    - npm install -g tslint typescript typedoc 
script:
    - npm run tsc:ci
    - npm run test:ci
    - npm run docs
notifications:
    slack: britishgasapp:R2pfdHMeBoHpHbPeFxtNjFyY